import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/admin/common.css',
                'resources/css/auth.css',
                'resources/css/guest.css',
                'resources/css/auth/register-validation.css',
                'resources/css/avatar/avatar.css',
                'resources/css/avatar/avatar-wizard-child.css',
                'resources/css/batch.css',
                'resources/css/child-theme.css',
                'resources/css/dashboard.css',
                'resources/css/profile/timezone.css',
                'resources/css/profile/group-edit.css',
                'resources/css/notifications.css',
                'resources/css/sidebar.css',
                'resources/css/tags.css',
                'resources/css/reports/performance.css',
                'resources/css/reports/member-summary-pdf.css',
                'resources/css/tasks/pending-approvals.css',
                'resources/css/tasks/search-results.css',
                'resources/css/tokens/history.css',
                'resources/css/tokens/purchase.css',
                'resources/css/subscriptions/select-plan.css',
                'resources/css/welcome.css',
                
                // Portal site assets
                'resources/css/portal-common.css',
                'resources/css/portal-features.css',
                'resources/css/portal/guide-navigation.css',
                
                'resources/js/app.js',
                'resources/js/admin/common.js',
                'resources/js/auth/login.js',
                'resources/js/auth/register-validation.js',
                'resources/js/avatar/avatar-controller.js',
                'resources/js/avatar/avatar-edit.js',
                'resources/js/avatar/avatar-form.js',
                'resources/js/avatar/avatar-wizard-child.js',
                'resources/js/common/notification-polling.js',
                'resources/js/common/sidebar.js',
                'resources/js/common/validation-core.js',
                'resources/js/components/search-modal.js',
                'resources/js/dashboard/dashboard.js',
                'resources/js/dashboard/header.js',
                'resources/js/dashboard/task-search.js',
                'resources/js/dashboard/tab-switch.js',
                'resources/js/dashboard/bulk-complete.js',
                'resources/js/dashboard/tag-modal.js',
                'resources/js/dashboard/task-modal.js',
                'resources/js/dashboard/tag-tasks-modal.js',
                'resources/js/dashboard/group-task.js',
                'resources/js/dashboard/group-task-detail.js',
                'resources/js/group-tasks/index.js',
                'resources/js/group-tasks/edit.js',
                'resources/js/infinite-scroll.js',
                'resources/js/dashboard/infinite-scroll-init.js',
                'resources/js/batch/scheduled-task-controller.js',
                'resources/js/notifications/notifications.js',
                'resources/js/notifications/admin-notifications.js',
                'resources/js/notifications/notification-search.js',
                'resources/js/reports/performance.js',
                'resources/js/reports/monthly-report.js',
                'resources/js/profile/profile-validation.js',
                'resources/js/group-link-children.js',
                // 'resources/js/sidebar/sidebar-store.js',
                'resources/js/tags/tags.js',
                'resources/js/tasks/pending-approvals.js',
                'resources/js/tasks/approval-task-detail-modal.js',
                'resources/js/tasks/search-tasks.js',
                'resources/js/tokens/history.js',
                'resources/js/tokens/purchase.js',
                'resources/js/subscriptions/select-plan.js',
                'resources/js/welcome-chart.js',
                
                // Portal site assets (JavaScript)
                'resources/js/portal/guide-navigation.js',
            ],
            refresh: true,
        }),
    ],
});