version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "task-service"
          ContainerPort: 3000
Hooks:
  - BeforeInstall: "scripts/before_install.sh"
  - ApplicationStart: "scripts/application_start.sh"
  - ApplicationStop: "scripts/application_stop.sh"
  - ValidateService: "scripts/validate_service.sh"