#!/bin/bash

# SVGからPNGへの変換スクリプト
# Stripe用商品画像生成

echo "==================================="
echo "Stripe商品画像PNG変換"
echo "==================================="

# 変換方法の選択
echo ""
echo "以下のいずれかの方法でPNG変換を行ってください："
echo ""
echo "【方法1】オンラインツール（最も簡単）"
echo "----------------------------------------"
echo "1. https://cloudconvert.com/svg-to-png にアクセス"
echo "2. family-plan-product-image-ja.svg をアップロード"
echo "3. 「Convert」をクリックしてダウンロード"
echo "4. ファイル名を family-plan-product-image.png に変更"
echo "5. enterprise-plan-product-image-ja.svg も同様に変換"
echo "6. ファイル名を enterprise-plan-product-image.png に変更"
echo ""
echo "【方法2】Webブラウザ（Chrome/Firefox）"
echo "----------------------------------------"
echo "1. SVGファイルをブラウザで開く"
echo "2. 右クリック → 「検証」→ Console"
echo "3. 以下を貼り付けて実行:"
echo ""
echo "const canvas = document.createElement('canvas');"
echo "canvas.width = 1200;"
echo "canvas.height = 630;"
echo "const ctx = canvas.getContext('2d');"
echo "const img = new Image();"
echo "img.onload = () => {"
echo "  ctx.drawImage(img, 0, 0);"
echo "  canvas.toBlob(blob => {"
echo "    const url = URL.createObjectURL(blob);"
echo "    const a = document.createElement('a');"
echo "    a.href = url;"
echo "    a.download = 'output.png';"
echo "    a.click();"
echo "  });"
echo "};"
echo "img.src = 'data:image/svg+xml;base64,' + btoa(document.documentElement.outerHTML);"
echo ""
echo "【方法3】Docker経由でImageMagickを使用"
echo "----------------------------------------"
echo "docker run --rm -v \$(pwd):/work dpokidov/imagemagick:7.1.1-15 \\"
echo "  convert /work/family-plan-product-image-ja.svg \\"
echo "  -resize 1200x630 /work/family-plan-product-image.png"
echo ""
echo "docker run --rm -v \$(pwd):/work dpokidov/imagemagick:7.1.1-15 \\"
echo "  convert /work/enterprise-plan-product-image-ja.svg \\"
echo "  -resize 1200x630 /work/enterprise-plan-product-image.png"
echo ""
echo "==================================="
echo "変換後、以下を確認してください："
echo "- family-plan-product-image.png (1200x630px)"
echo "- enterprise-plan-product-image.png (1200x630px)"
echo "- ファイルサイズが2MB未満"
echo "==================================="
